/*
GB Maps ギビマップ - © Karya IT (http://www.karyait.net.my/) 2012-2014. All rights reserved. 
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

GB Maps ギビマップ by Karya IT is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. Based on a work at https://code.google.com/p/gbmaps/. Permissions beyond the scope of this license may be available at https://developers.google.com/readme/terms. Google Maps - ©2014 Google.

Code license : Apache License 2.0

Main GB Maps ギビマップ Website : http://gbmaps.karyait.net.my/ or http://gbmaps.blogspot.com

Development site (programming) : https://github.com/karyait/gbmaps & https://code.google.com/p/gbmaps/
Personal blog for GB Maps ギビマップ (design algorithm) : http://blogkaryait.wordpress.com/tag/gbmaps/


File : my.js
purpose : language file
type : development release
version : 1.1.0
build : 
last update : 25 October 2014 2:00am (GMT 8+)

*/

jquery_lang_js.prototype.lang.my = {
	'text':'teks',
	'Open File':'Buka Fail',
	'Find location':'Cari Lokasi',
	'New Map':'Peta Baru',
	'Default location':'Lokasi lalai',
	'Export/Save map':'Eksport/Simpan Peta',
	'Import/Open map':'Import/Buka Peta',
	'Options':'Opsyen',
	'Add Point':'Tambah titik',
	'Route Color ...':'Warna route ...',
	'Maps':'Peta',
	'Draw':'Lukis',
	'Build Route':'Bina laluan',
	'Help':'Bantu',
	'Manual':'Panduan',
	'GB Maps':'GB Maps',
	'Language':'Bahasa',
	'Invert Line':'Terbalikan Garis',
	'Clear All':'Hapus Semua',
	'Troubleshooting':'Penyelesai Masalah',
	'System Requirements':'Keperluan Sistem',
	'Credits':'Penghargaan',
	'Abouts':'Perihal',
	'Build':'Bina',
	'Objects List':'Senarai objek',
	'Lines List':'Senarai Garis',
	'BVE Rail Type':'Jenis Rail BVE',
	'Theme Selection':'Pemilih Tema',	
	'File name':'Nama fail',
	'Paste &lt;Ctrl+V&gt; GB Maps ギビマップ data in the following text box.':'Tampal &lt;Ctrl+V&gt; data GB Maps ギビマップ ke dalam kotak teks yang berikut.',
	'Import ...':'Import ...',
	'Find ...':'Mencari...',
	'Find location (e.g : "Kanita, Japan" OR "Rawang"): ':'Mencari lokasi (cth: "Kanita, Jepun" atau "Rawang"):',
	'System Requirement':'Keperluan sistem',
	'Measure distance.':'Ukuran jarak.',
	'Measure angle.':'Ukuran sudut.',
	'Undo':'Undo',
	'Redo':'Redo',
	'Reload Map to default location?':'Muat semula peta ke lokasi lalai?',
	'Set current map as default?':'Tetapkan peta semasa sebagai lalai?',
	'OR':'ATAU',
	'Paste &lt;Ctrl+V&gt; GB Maps ギビマップ data in the following text box.':'Tampal &lt;Ctrl+V&gt; data GB Maps ギビマップ ke petak teks berikut.',
	'If file saving unsupported by your browser, please copy this texts and save file manually with your text editor (e.g : Notepad). Select &lt;Ctrl+A&gt; and copy &lt;Ctrl+C&gt; the following text to your text editor.':'Jika menyimpan fail tidak disokong oleh pelayar web anda, sila salin di atas dan simpan secara manual dengan aplikasi teks editor anda. (cth : Notepad). Pilih semua &lt;Ctrl+A&gt; dan salin &lt;Ctrl+C&gt; teks di atas ke teks editor anda.',
	'Save':'Simpan',
	'Close':'Tutup',
	'Legends':'Petunjuk',
	'This software also contains content from various sources. Copyright of the contents are as described in the original source.':'Perisian ini juga mengandungi kandungan daripada pelbagai sumber. Hak cipta kandungan itu adalah seperti yang dinyatakan dalam sumber asal.',
	'Build route ...':'Membina laluan ...',
	'Select theme':'Pilih tema',
	'Developer ID':'ID Pemaju',
	'Default Gauge':'Gauge lalai',
	'Default Cant':'Kant Lalai',
	'Default Offset':'Ofset lalai',
	'BVE structures list':'Senarai struktur BVE',
	' OR add new list':' ATAU tambah senarai baru',
	'or':'atau',
	'Clear List':'Kosongkan senarai',
	'default API version (latest)':'versi API lalai (tekini)',
	'experimental API':'API ujikaji',
	'frozen version':'versi kaku',
	'Please refresh this page if you change the API version.':'Sila muat semula halaman ini jika anda menukar versi API.',
	'Update':'Kemas Kinikan',
	'Cancel':'Batal',
	'Development Info':'Info Pembangunan',
	'Framework / plugins used:':'Framework / plugin digunakan:',
	'Development platform':'Platform pembangunan',
	'Loading ...':'Memuat ...',
	'Please wait ...':'Sila tunggu ...',
	'Suggested Cant Size':'Cadangan saiz kant',
	'Please select any two points, and the distance should be less than 12.5 km. Maximum number of samples for elevation data along path in Google Maps is 512 samples. The length of each sample is 25 meters.':'Sila pilih mana-mana dua titik, jaraknya hendaklah kurang daripada 12.5 km. Bilangan maksimum sampel untuk data ketinggian sepanjang laluan dalam Peta Google adalah 512 sampel. Jarak setiap sampel ialah 25 meter.',
	'Point 1':'Titik 1',
	'Point 2':'Titik 2',
	'View Elevation':'Papar Ketinggian',
	'Reset':'Reset',
	'Rail pitch':'Cerun Rail',
	'Pitchs':'Cerun',
	'Heights':'Ketinggian',
	'Structures':'Struktur',
	'Details code':'Butiran kod',
	'calculate track pitch':'kira kecerunan trek',
	'set pitch':'tetapkan cerun',
	'(1/1000) at':'(1/1000) di',
	'+  : uphill, - : downhill, 0 : level':'+: mendaki, -: menurun, 0: mendatar',
	'from':'dari',
	'to':'ke',
	', set':', tetapkan',
	'Fixed track height':'Ketinggian trek tetap',
	'Auto height (generate height per segment)':'Ketinggian auto (jana ketinggian per segmen)',
	'Set':'Tetapkan',
	'type of structure':'jenis struktur',
	'location':'lokasi',
	'start / end':'mula / tamat',
	'Start':'Mula',
	'End':'Tamat',
	'Start point at':'Mula pada titik',
	'Elevation':'Ketinggian',
	'Track':'Trek',
	'Suggestion':'Cadangan',
	'Suggested value (Technical Standard for Japanese Railway):\nmaximum gradient for ordinary railways:\n-  on tracks traveled by trains pulled by locomotive : 25/1000\n- track used only by trains powered by linear induction motor trains : 60/1000\n- the maximum gradient in turnout areas shall be 25/1000\n- maximum gradient in the stopping areas shall be 5/1000. however, it may be 10/1000\nin the areas not used for parking or coupling/decoupling of the rolling stock\n\nmaximum gradient of Shinkansen railways\n- in the traveling areas : 25/1000\n- maximum gradient in the stopping areas shall be 3/1000':'Cadangan nilai (Technical Standard for Japanese Railway):\nkecerunan maksimum untuk keretapi biasa:\n-  pada trek dilalui oleh kereta api ditarik oleh lokomotif : 25/1000\n- Trek hanya digunakan oleh kereta api dikuasakan oleh motor induksi linear : 60/1000\n- kecerunan maksimum di belokan keluar hendaklah 25/1000\n- kecerunan maksimum di kawasan berhenti hendaklah 5/1000. walau bagaimanapun, adalah mungkin 10/1000\ndi kawasan2 tidak digunakan untuk meletak atau pemasangan/nyahpasangan keretapi\n\nkecerunan maksimum trenlaju\n- dalam kawasan perjalananan : 25/1000\n- kecerunan maksimum di kawasan berhenti hendaklah 3/1000',
	'Apply Structure':'Aplikasi struktur',
	'Reset All':'Reset Semula',
	'Rail Curve':'Lengkuk Rel',
	'Design Speed':'Halaju rekabentuk',
	'enforce track speed limit':'kuat kuasakan hadlaju',
	'Gauge':'Gauge',
	'Cant':'Kant',
	'Suggested value:\nJapan - conventional lines (narrow gauge 1067mm) : 105mm\nJapan - Shinkansen (standard gauge 1435mm) : 200mm':'Cadangan nilai:\nJapan - laluan konvensional (narrow gauge 1067mm) : 105mm\nJapan - Shinkansen (standard gauge 1435mm) : 200mm',
	'Suggested curve radius':'Cadangan jejari lengkung',
	'any reasonable value OR roundup to common value based on speed limit.\n\nfor example : minimum curve radius 160 m for ordinary railways\n(Technical Standard for Japanese Railway)':'apa-apa nilai yang munasabah ATAU genapkan kepada nilai biasa berdasarkan had laju \n\ncontoh: jejari lengkung minimum bagi kereta api biasa adalah 160 m\n(Standard Teknikal Keretapi Jepun)',
	'please refresh this value if you don\'t change any above values':'sila muat semula nilai ini jika anda tidak menukar sebarang nilai di atas',
	'Rail index (type)':'Indeks rel (jenis)',
	'Transition Curve':'Lengkuk Peralihan',
	'Curve radius':'Jejari Lengkuk',
	'Circular rail index':'Indeks rel bulatan',
	'Calculation method':'Metod Kiraan',
	'Parallel Line':'Garis Selari',
	'Parallel line offset':'Ofset garis selari',
	'Position':'Kedudukan',
	'(+) to the right':'(+) ke kanan',
	'(-) to the left':'(-) ke kiri',
	'Cracks between tracks':'Cracks antara trek',
	'Duplicate?':'Pendua?',
	'whole line':'seluruh garis',
	'between two point':'antara dua titik',
	'(click two markers to select)':'(klik penanda untuk memilih)',
	'belokan keluar (suiz) dari laluan utama pada permulaan (jarak pemula = 0),':'',
	'switch length (25/50/75...)':'panjang suiz (25/50/75...)',
	'belokan keluar (suiz) dari laluan utama pada penghujung (jarak penamat = 0),':'',
	'Create':'Cipta',
	'Combine two lines':'Gabung dua garis',
	'Combine two line at the two nearest points. Click another line and click Join button.':'Mengabungkan dua garis pada dua titik terhampir. Klik garis lain dan klik butang Gabungkan',
	'line 1':'garis 1',
	'line 2':'garis 2',
	'Join':'Gabungkan',
	'Insert Note':'Masukan nota',
	'Insert note or comment for selected point.':'Masukan nota atau komen pada titik dipilih',
	'Marker Setting':'Tetapan Penanda',
	'Marker':'Penanda',
	'Raw Datas':'Data Mentah',
	'line id':'id garis',
	'marker no':'no marker/titik',
	'route id':'id laluan',
	'route title':'tajuk laluan',
	'position':'kedudukan',
	'Locked':'Dikunci',
	'pole':'tiang',
	'railindex':'indek rel',
	'note':'nota',
	'Caution ! Please edit with caution. Improper editing will broke the data consistency, and cause program failure.':'Amaran! Sila edit dengan berhati-hati. Penyuntingan yang tidak betul akan memecah konsisten data, dan menyebabkan kegagalan program.',
	'Track Setting':'Tetapan trek',
	'description':'keterangan',
	'default rail type':'jenis rel lalai',
	'train':'tren',
	'max speed':'halaju maksimum',
	'target simulator':'simulator sasaran',
	'remark':'komen',
	'starting station':'stesen mula',
	'terminal station':'stesen terminal',
	'max design speed':'halaju maksimum rekabentuk',
	'background':'latar',
	'KM stone':'batu KM',
	'Station Near Sign':'Tanda Stesen Hampir',
	'New Line ...':'Baris baru ...',
	'Create new line with two points.':'Mencipta garis baru dengan dua titik.',
	'1st point latitude':'latidud titik 1',
	'1st point longitude':'longitud titik 1',
	'2nd point latitude':'latidud titik 2',
	'2nd point longitude':'longitud titik 2',
	'Create line':'Cipta garis',
	'Route Colour':'Warna Laluan',
	'Select route':'Pilih laluan',
	'Choose colour':'Pilih warna',
	'Colour Code':'Kod warna',
	'Insert Crossing':'Masukkan Lintasan',
	'Crossing type':'Jenis lintasan',
	'Insert over-bridge':'Masukan jejantas',
	'Over bridge':'Jejantas',
	'Adjustment':'Pelarasan',
	'Distance correction (optional)':'Pembetulan jarak (opsyenal)',
	'Height correction (optional)':'Pembetulan tinggi (opsyenal)',
	'Angle correction (optional)':'Pembetulan sudut (opsyenal)',
	'Insert':'Masukkan',
	'type':'jenis',
	'selected bridge length':'panjang jambatan dipilih',
	'Insert River':'Masukkan Sungai',
	'river':'sungai',
	'width':'lebar',
	'river bank':'tebing sungai',
	'ground after':'dataran selepas',
	'Update Ground':'Kemas kini Dataran',
	'ground structure':'struktur dataran',
	'Widen parallel tracks':'Pelebaran trek selari',
	'Widening the distance between two parallel track center.':'Melebarkan jarak antara dua tengah trek selari.',
	'track 1':'trek 1',
	'track 2':'trek 2',
	'point b':'titik b',
	'point e':'titik e',
	'point b\' (if not exist, please select point a\')':'titik b\'(jika tidak wujud, sila pilih titik a\')',
	'point e\' (if not exist, please select point f\')':'titik e\'(jika tidak wujud, sila pilih titik f\')',
	'point b\' on track 2 must perpendicular to point b on track 1.':'titik b\' di trek 2 mestilah berserenjang dengan titik b di trek 1.',
	'point e\' on track 2 must perpendicular to point e on track 1.':'titik e\' di trek 2 mestilah berserenjang dengan titik e di trek 1.',
	'initial turnout length':'panjang belokan pemula',
	'initial turnout width':'lebar belokan pemula',
	'Different slope ratio for the second track.(optional)':'Nisbah condong berbeza untuk trek kedua.(opsyenal)',
	'turnout length':'panjang belokan',
	'turnout width':'lebar belokan',
	'end turnout length':'panjang belokan penamat',
	'end turnout width':'lebar belokan penamat',
	'Insert platform':'Masukan platform',
	'Type':'Jenis',
	'2nd line (parallel)':'Garis ke2 (selari)',
	'Create platform':'Cipta platform',
	'length':'panjang',
	'Station name':'Nama stesen',
	'Station ID':'ID stesen',
	'Duration':'Tempoh',
	'Stop sign':'Tanda Berhenti',
	'sec':'saat',
	'Cracks':'Crack',
	'Car(s)':'Gerabak',
	'Stop offset':'Ofset henti',
	'Train Stop':'Tren berhenti',
	'Left':'Kiri',
	'Right':'Kanan',
	'Insert Switch Between Two Parallel Tracks':'Masukkan suis antara dua trek selari',
	'both (X crossing)':'kedua-dua (lintasan X)',
	'1 to 2':'1 ke 2',
	'2 to 1':'2 ke 1',
	'Switch length':'Panjang suiz',
	'Insert flyover':'Masukkan jejambat',
	'Flyover':'Jejambat',
	'Flyover start':'Jejambat mula',
	'Target height':'Tinggi sasaran',
	'Pitch (+/- value)':'Cerun (nilai +/-)',
	'slope length':'panjang cerun',
	'Flyover end':'Jejambat tamat',
	'Insert Tunnel':'Masukkan Terowong',
	'tunnel':'terowong',
	'Invert Line':'Terbalikkan garis',
	'Invert markers index on selected line.':'Terbalikkan indeks penanda pada garis dipilih.',
	'Select line':'Pilih garis',
	'Link between lines':'Pautkan antara garis',
	'Select line and markers index.':'Pilih garis dan indeks penanda',
	'between marker index':'antara indeks penanda',
	'and':'dan',
	'Insert Dike':'Masukkan Benteng',
	'structure':'struktur',
	'Insert Hill Cut/Wall':'Masukkan genting/dinding',
	'Insert Poles':'Masukan Tiang',
	'Manual Pitch':'Cerun Manual',
	'pitch':'cerun',
	'BVE structures':'Struktur BVE',
	'Routes':'Laluan',
	'Stations':'Stesen',
	'Map Objects':'Objek2 Peta',
	'unable to create platform':'tidak dapat mencipta platform',
	'sorry! unable to create this type of platform on curve.':'maaf! tidak dapat mencipta platform jenis ini di atas lengkuk',
	'platform cross multi curve are not supported, please create platform manually':'platform merentasi berbilang lengkuk tidak disokong, sila cipta platform secara manual',
	'Sorry, please create platform manually.':'Maaf! sila cipta platform secara manual',
	'<br />curve length : ':'<br />panjang lengkok : ',
	'<br />arc distance : ':'<br />jarak sub lengkok : ',
	'<br />horizontal distance : ':'<br />jarak mendatar : ',
	'Distance at marker index : ':'Jarak pada indeks penanda : ',
	'), on line : ':'), pada garis : ',
	'Polyline distance : ':'Jarak poligaris : ',
	'Horizontal distance : ':'Jarak mendatar : ',
	'Vertical distance : ':'Jarak menegak : ',
	'<br>intersection angle θ : ':'<br>sudut persilangan θ : ',
	'<br>deflection angle Δ : ':'<br>sudut pesongan Δ : ',
	'Note : ':'Nota : ',
	'<br />Curve : ':'<br />Lengkuk : ',
	'<br />Trans. Curve : ':'<br />Lengkuk Peralihan : ',
	'<br />Pitch : ':'<br />Cerun : ',
	'<br />Side line(s) : ':'<br />Garis2 sisi : ',
	'Distance : ':'Jarak : ',
	'Intersection Angle : ':'Sudut persilangan : ',
	'Line Id : ':'Id garis : ',
	'Line ID : ':'ID garis : ',
	'<br />Polyline Length : ':'<br />Panjang poligaris : ',
	'Horizontal Length : ':'Panjang mendatar : ',
	'Vertical Length : ':'Panjang menegak : ',
	'Edit line':'Ubah garis',
	'Polygon Id : ':'Id poligon : ',
	'Marker Id : ':'Id penanda : ',
	'Location : ':'Lokasi : ',
	'Rectangle Id : ':'Id segiempat : ',
	'Area : ':'Luas : ',
	'Width : ':'Lebar : ',
	'Height : ':'Tinggi : ',
	'Circle Id : ':'ID Bulatan : ',
	'Radius : ':'Jejari : ',
	'Center : ':'Pusat : ',
	'    Marker index : ':'    Indeks penanda : ',
	'Click to stop line or shape editing, OR to move the map.':'Klik untuk henti ubah garis atau bentuk, ATAU untuk gerakkan peta.',
	'Draw a line (polyline)':'Melukis garisan (polyline)',
	'Draw a polygon. Not used in BVE code generator.':'Melukis poligon. Tidak digunakan dalam penjana kod BVE.',
	'Draw a circle. Not used in BVE code generator.':'Melukis bulatan. Tidak digunakan dalam penjana kod BVE.',
	'Draw a rectangle with two point. Not used in BVE code generator.':'Melukis segiempat dengan dua titik. Tidak digunakan dalam penjana kod BVE.',
	'Draw a marker on the map. Not used in BVE code generator.':'Melukis penanda di atas peta. Tidak digunakan dalam penjana kod BVE.',
	'Measure distance.':'Mengukur jarak.',
	'Measure angle.':'Mengukur sudut.',
	'Bridge':'Jambatan',
	'Hill cut':'Genting',
	'Dike':'Benteng',
	'Tunnel':'Terowong',
	'Flyover':'Jejambat',
	'sort rail index...':'sisih indeks rel...',
	'Setting':'Tetapan',
	'Add Note':'Tambah nota',
	'Update Pitch':'Kemas kini Cerun',
	'Insert Hillcut':'Masukkan Genting',
	'Insert Platform@Station':'Masukkan Platform@Stesen',
	'Insert Overbridge':'Masukkan Jejantas',
	'Insert Bridge':'Masukkan Jambatan',
	'Insert Track Switching':'Masukkan Suiz Trek',
	'Circular curve':'Lengkuk Bulat',
	'Transition@relexation curve (BVE 5 only)':'Lengkuk peralihan (BVE 5 sahaja)',
	'Remove line':'Hapus garis',
	'Add new point to current line':'Tambah titik ke garis semasa',
	'Split line':'Pisah garis',
	'Join @ combine two lines':'Gabung dua garis',
	'Create parallel line':'Cipta garis selari',
	'Line pitch @ gradient':'Kecerunan garis',
	'Edit polygon':'Edit poligon',
	'Remove line':'Hapus garis',
	' Edit':' Edit',
	' Remove':' Hapus',
	'Remove':'Hapus',
	' Properties':' Properti',
	'Properties':'Properti',
	'Remove marker':'Hapus penanda',
	'Remove rectangle':'Hapus segi empat',
	'Remove circle':'Hapus bulatan',
	'Insert Flyover':'Masukkan Jejambat',
	'Update Platform Type':'Kemas kini jenis platform',
	'This point is the end of the platform, please update the starting point of the platform.':'Titik ini adalah hujung platform, sila kemas kini titik awal platform.',
	'- select -':'- pilih -',
	'turnout (switch) from main line at start (start offset = 0),':'belokan(suiz) dari trek utama di titik mula (offset mula =0),',
	'turnout (switch) back to main lain at the end (end offset = 0),':'belokan(suiz) kembali ke trek utama di titik hujung (offset tamat =0),',
	'meter':'meter',
	'Caution! Only curves and bve structures will be preserved.\nParalell lines, elevations data will be removed.\nDo you want to continue?':'Awas! Hanya data lengkuk dan struktur bve akan dikekalkan.\nData garis2 selari, paras akan dihapuskan.\nAdakah anda ingin teruskan?',
	'remove note at this marker?':'hapuskan nota di penanda ini?',
	'note has be removed at that marker.':'',
	'Reload Map to default location?':'Muat semula peta ke lokasi lalai?',
	'Set current map as default?':'Tetapkan peta semasa sebagai lalai?',
	'Clear all items?':'Hapuskan semua item?',
	'unable to verify line : ':'tidak dapat mengesahkan garis : ',
	'Please remove current curve at this marker : ':'Sila hapuskan lengkuk semasa di penanda ini : ',
	'Sorry! you can\'t create curve at the beginning of the line.':'Maaf! anda tidak boleh mencipta lengkuk di permulaan garis.',
	'Sorry! you can\'t create curve at the end of the line.':'Maaf! anda tidak boleh mencipta lengkuk di penghujung garis.',
	'Caution! curve overlapped with previous curve.':'Awas! lengkuk bertindih dengan lengkuk sebelumnya.',
	'Caution! curve overlapped with next curve.':'Awas! lengkuk bertindih dengan lengkuk sesudahnya.',
	'Caution! Unable to fit curve at the intersection. Curve is too big, please reduce curve radius or design speed.':'Awas! Tidak dapat memuatkan lengkuk di persilangan ini. Lengkuk adalah terlalu besar, sila kecilkan jejari lengkuk atau kurangkan kelajuan reka bentuk.',
	'Curve Id : ':'Id Lengkuk : ',
	'<br>Line id : ':'<br>Id garis : ',
	' index : ':' indeks : ',
	'<br>radius : ':'<br>jejari : ',
	' m<br>design speed : ':' m<br>halaju reka bentuk : ',
	' km/h<br>cant : ':' km/h<br>kant : ',
	'<br>curve length : ':'<br>panjang lengkuk : ',
	' m<br>tangent length : ':' m<br>panjang tangen : ',
	'Please remove current transition curve at this marker : ':'Sila hapuskan lengkuk peralihan semasa di penanda ini : ',
	'Sorry! unable to draw curve on stright line.':'Maaf! tidak dapat melukis lengkuk di atas garis lurus.',
	'Sorry! unable to draw transition curve on stright line.':'Maaf! tidak dapat melukis lengkuk peralihan di atas garis lurus.',
	'Caution: the deflection angle is too small to introduce transition curve. \nCurrent deflection angle is : ':'Awas! sudut pesongan adalah terlalu kecil untuk menyisipkan lengkuk peralihan. \nSudut pesongan semasa adalah : ',
	'Caution: Minimum radius for this deflection angle is : ':'Awas: Jejari minimum untuk sudut pesongan ini adalah : ',
	'Caution! curve overlapped with previous transition curve.':'Awas! lengkuk bertindih dengan lengkuk peralihan sebelumnya.',
	'Caution! curve overlapped with next transition curve.':'Awas! lengkuk bertindih dengan lengkuk peralihan sesudahnya.',
	'Caution! Unable to fit transition curve at the intersection. Transition curve is too big, please reduce curve radius or the design speed.':'Awas! Tidak dapat memuatkan lengkuk peralihan di persilangan ini. Lengkuk peralihan adalah terlalu besar, sila kecilkan jejari lengkuk atau kurangkan kelajuan reka bentuk.',
	'Sorry! unable to determine next heading direction.':'Maaf! tidak dapat menentukan arah haluan seterusnya.',
	'Geocode was not successful for the following reason: ':'Geocode gagal atas sebab berikut : ',
	'<strong> Caution!: </strong> curve overlapped with previous curve.<br />':'<strong> Awas!: </strong> lengkuk bertindih dengan lengkuk sebelumnya.<br />',
	'<strong> Caution!: </strong> curve overlapped with next curve.<br />':'<strong> Awas!: </strong> lengkuk bertindih dengan lengkuk seterusnya.<br />',
	'<strong> Caution!: </strong> Unable to fit curve at the intersection.<br />Curve is too big, please reduce curve radius or design speed.<br />':'<strong> Awas!: </strong> Tidak dapat memuatkan lengkuk di persilangan ini.<br />Lengkuk terlalu besar, sila kecilkan jejari atau kurangkan kelajuan reka bentuk.<br />',
	'<strong>Caution:</strong> the deflection angle is too small to introduce transition curve. <br />Current deflection angle is : ':'<strong>Awas:</strong> sudut pesongan adalah terlalu kecil untuk menyisipkan lengkuk peralihan. <br />Sudut pesongan semasa adalah : ',
	'<strong>Caution:</strong> Minimum radius for this deflection angle is : ':'<strong>Awas:</strong> Jejari minimum untuk sudut pesongan ini adalah : ',
	'Transition curve is not required for this setting.':'Lengkuk peralihan tidak diperlukan untuk tetapan ini.',
	'Transition curve is required for this setting.':'Lengkuk peralihan tidak diperlukan untuk tetapan ini.',
	'<strong> Caution!: </strong> overlapped with previous transition curve.<br />':'<strong> Awas!: </strong> lengkuk bertindih dengan lengkuk peralihan sebelumnya.<br />',
	'<strong> Caution!: </strong> curve overlapped with next transition curve.<br />':'<strong> Awas!: </strong> lengkuk bertindih dengan lengkuk peralihan sesudahnya.<br />',
	'<strong> Caution!: </strong> Unable to fit transition curve at the intersection.<br />Transition curve is too big, please reduce curve radius or the design speed.<br />':'<strong> Caution!: </strong> Tidak dapat memuatkan lengkuk peralihan di persilangan ini.<br />Lengkuk peralihan adalah terlalu besar, sila kecilkan jejari lengkuk atau kurangkan kelajuan reka bentuk.<br />',
	'The elevation at this point is<br> ':'Paras pada titik ini adalah<br> ',
	'No results found':'Tiada keputusan diperolehi',
	'Elevation service failed due to: ':'Servis elavasi gagal disebabkan : ',
	'Elevation (m)':'Paras (m)',
	'Distance (m) + ':'Jarak (m) + ',
	'<br>total transition curve length : ':'<br>jumlah panjang lengkuk peralihan : ',
	'<br>total tangent from intersection : ':'<br>jumlah tangen dari persilangan : ',
	'<br>circular curve length Lc : ':'<br>panjang lengkuk bulat Lc : ',
	'<br>shift : ':'<br>anjakan : ',
	'<br>spiral curve length Ls : ':'<br>panjang lengkuk spiral Ls : ',
	'<br>cant : ':'<br>kant : ',
	'the note has succesfully insert at ':'nota berjaya dimasukkan di ',
	'Unsupported browser : ':'Pelayar tidak disokong : ',
	'Local cookie not supported.\n':'Cokie tempatan tidak disokong.\n',
	'File API not supported by this browser.\n':'API fail tidak disokong oleh pelayar ini.\n',
	'\nNote: Please check for browser compatibility.':'\nNota: Sila semak keserasian pelayar web.',
	'Reading data ...':'Membaca data ...',
	'Loading : polylines ...':'Memuat : polygaris ...',
	'Loading : polylines and curves ...':'Memuat : polygaris dan lengkuk ...',
	'Loading : curves ...':'Memuat : lengkuk ...',
	'Loading : transition curves ...':'Memuat : lengkuk peralihan ...',
	'Loading : dotMarkers ...':'Memuat : penanda ...',
	'Reading polylines ...':'Membaca poligaris ...',
	'Updating lines id reference ...':'Kemas kinikan rujukan id ...',
	'Loading : rectangles ...':'Memuat : segiempat ...',
	'Loading : circles ...':'Memuat : bulatan ...',
	'Loading : polygons ...':'Memuat : poligon ...',
	'm(^_^)m ... done loading, thank you for waiting.':'m(^_^)m ... selesai memuat, terima kasih kerana menunggu.',
	'marker index not defined':'indeks penanda tidak ditakrif.',
	'Station ID already exists.':'ID stesen telah wujud.',
	'sorry! unable to create platform on curve.':'Maaf! tidak dapat mencipta platfrom di atas lengkuk.',
	'warning! array not updated!':'perhatian! array tidak dikemas kini!',
	'track setting updated':'tetapan trek dikemas kini',
	'marker setting updated':'tetapan penanda dikemas kini',
	'invalid 2nd line! please choose a valid parallel line.':'garis kedua tidak sah! sila pilih garis selari yang sah.',
	'invalid 2nd line! the 2nd line is not parallel with main line.':'garis kedua tidak sah! garis kedua tidak selari dengan garis utama',
	'please select either start point or end point, tq':'sila pilih sama ada titik mula atau penamat, tk.',
	'please select the structure type':'sila pilih jenis struktur',
	'Setting updated.':'Tetapan dikemas kinikan.',
	'form type updated.':'jenis form dikemas kinikan.',
	'The File APIs are not supported in this browser.':'API fail tidak disokong oleh pelayar web ini.',
	'please state your start point and end point':'sila nyatakan titik mula dan titik penamat',
	'Please select any two point on line : ':'Sila pilih sebarang dua titik pada garis : ',
	'line id not defined':'id garis tidak ditakrif',
	'trackname not defined':'nama trek tidak ditakrif',
	'route not defined':'laluan tidak ditakrif',
	'please choose target simulator':'sila pilih simulator sasaran',
	'gauge not defined':'tolok tidak ditakrif',
	'default rail type not defined':'jenis rel lalai tidak ditakrif',
	'Error! Unable to determine which line to invert.':'Ralat! tidak dapat menentukan garis yang akan diterbalikan.',
	'Please define at least one route.\nConfigure line setting ...':'Sila takrifkan sekurangnya satu laluan.\nSila konfigur tetapan garis.',
	'please enter latitude and longitude value properlly! NaN error, unable to translate inputs to numbers.':'sila masukkan nilai latitud dan logitud dengan betul! Ralat bukan nombor, tidak dapat menukar masukkan ke nombor.',
	'please fill all fields with appropriate latitude and longitude value!':'sila isikan semua medan dengan nilai2 latitud dan longitud!',
	'Please state each line indexes':'Sila nyatakan setiap indeks garis',
	'Either lines is not valid.':'Salah satu garis adalah tidak sah.',
	'Drawing Tools':'Alatan melukis',
	'Stop drawing line/shape.':'Henti lukis garis atau bentuk',
	'Stop drawing line/shape.':'Henti lukis garis atau bentuk',
	'Draw a line (polyline).':'Lukis garisan (poligaris).',
	'Draw a shape (polygon).':'Lukis bentuk (poligon).',
	'Draw a circle.':'Lukis bulatan.',
	'Draw a rectangle.':'Lukis segi empat.',
	'Measure distance between two points.':'Mengukur jarak antara dua titik.',
	'Measure angle with three points.':'Mengukur sudut dengan tiga titik.',
	'InfoWindows Line':'InfoWindows Garis',
	'Edit Line':'Ubah Garis',
	'Delete Line':'Hapus Garis',
	'Split Line':'Pisah Garis',
	'Join Two Lines':'Gabung Dua Garis',
	'Create Parallel Lines':'Cipta Garis Selari',
	'Line Gradient':'Kecerunan Garis',
	'Line Setting':'Tetapan Garis',
	'InfoWindows Line/Curve Markers':'InfoWindows Penanda Garis/Lengkuk',
	'Create Curve':'Cipta Lengkuk',
	'Create Transition Curve':'Cipta Lengkuk Peralihan',
	'Widen Parallel Lines':'Melebarkan Garis Selari',
	'Link Lines':'Pautkan Garis',
	'Insert Road Crossing':'Masukan Lintasan',
	'Insert Over Bridge':'Masukan Jejantas',
	'Insert Platform/Station':'Masukan Platform/Stesen',
	'Insert Hill-cut/Wall':'Masukan Genting/Dinding',
	'Insert/Update Pole':'Masukan/Kemas kini Tiang',
	'Manual Gradient':'Kecerunan Manual',
	'Insert Comment':'Masukan Komen',
	'InfoWindows Polygon':'InfoWindows Poligon',
	'Edit Polygon':'Ubah Poligon',
	'Remove Polygon':'Hapus Poligon',
	'Polygon Setting':'Tetapan Poligon',
	'InfoWindows Circle':'InfoWindows Bulatan',
	'Remove Circle':'Hapus Bulatan',
	'Circle Setting':'Tetapan Bulatan',
	'InfoWindows Rectangle':'InfoWindows Segi empat',
	'Remove Rectangle':'Hapus Segi empat',
	'Rectangle Setting':'Tetapan Segi empat',
	'InfoWindows Marker':'InfoWindows Penanda',
	'Remove Marker':'Hapus Penanda',
	'Curve Start':'Lengkuk Mula',
	'Curve End':'Lengkuk Tamat',
	'Curve Center':'Pusat Lengkuk',
	'Transition Curve Start/End':'Lengkuk Peralihan Mula/Tamat',
	'Hill Cut/Wall':'Genting/Dinding',
	'Overbridge':'Jejantas',
	'Ground Change':'Dataran Ditukar',
	'Platform Start/End':'Platform Mula/Tamat',
	'Road Crossing':'Lintasan Keretapi',
	'Pole':'Tiang',
	'Pitch':'Kecerunan',
	'River':'Sungai',
	'Ruler Marker':'Penanda Pembaris',
	'Custom Marker on Curve':'Penanda pada Lengkuk',
	'Angle':'Sudut',
	'Default Marker on Polyline/Polygon':'Penanda lalai pada Poligaris/Poligon',
	'Caution! Javascript file only, i.e. with ".js" file extension.':'Awas! Fail JavaScript sahaja, iaitu dengan sambungan fail ".js".',
	'Don\'t forget to select the file after you create the list.':'Jangan lupa untuk menanda fail selepas anda mencipta senarai.',
	//'':'',
	//'':'',
}